pipeline {
	agent any
	environment {
		DOCKERHUB_CREDENTIALS = credentials('dockerhub')
		//DOCKERHUB_PASS = credentials('dockerhub')
	}
	stages {

		stage("Check Workspace") {
            		steps {
                		sh 'pwd'  // Print current directory (workspace)
                		sh 'ls'   // List files in current directory (workspace)
            		}
        	}
		stage("Building the Student Survey Image"){
			steps{
				script{
					checkout scm
					sh 'echo ${BUILD_TIMESTAMP}'
					
					// Use Jenkins credentials binding to securely login to DockerHub
			        withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
			                	
						sh "echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin"
			                        
						env.BUILD_TIMESTAMP = "${BUILD_TIMESTAMP}".replaceAll(/[^\w.-]/, '-')
						def dockerfilePath = 'survey-application'
           				def customImageTag = "johnstephengutam/mywebapp2:${env.BUILD_TIMESTAMP}"
            			docker.build(customImageTag, dockerfilePath)
			        } 
				}
			}
		}
		stage("Pushing Image to DockerHub"){
			steps{
				script{
					sh "docker push johnstephengutam/mywebapp2:${env.BUILD_TIMESTAMP}"
				}
			}
		}
		stage("Deploying to Rancher as single pod"){
			steps{
				sh "kubectl set image deployment/hw3-deployment container-0=johnstephengutam/mywebapp2:${env.BUILD_TIMESTAMP}"
			}
		}
	}
}
